version: "3"

vars:
  ICON_VERSION: "0.1.3"
  WEB_VERSION: "0.1.3"

tasks:
  icon-tag:
    cmds:
      - git tag -d icons-v{{.ICON_VERSION}} 2>/dev/null || true
      - git push origin :refs/tags/icons-v{{.ICON_VERSION}} 2>/dev/null || true
      - git tag icons-v{{.ICON_VERSION}}
      - git push origin icons-v{{.ICON_VERSION}}

  icon-web-tag:
    cmds:
      - git tag -d icon-web-v{{.WEB_VERSION}} 2>/dev/null || true
      - git push origin :refs/tags/icon-web-v{{.WEB_VERSION}} 2>/dev/null || true
      - git tag icon-web-v{{.WEB_VERSION}}
      - git push origin icon-web-v{{.WEB_VERSION}}

  tag-all:
    desc: Tag all packages with the version in the Taskfile
    cmds:
      - task: icon-tag
      - task: icon-web-tag
