// Build script: optimize /src/svgs and generate /src/index.ts
import fs from 'node:fs/promises';
import path from 'node:path';
import { optimize } from 'svgo';

const root = path.resolve(process.cwd(), 'packages/icons');
const svgsDir = path.join(root, 'src', 'svgs');
const outFile = path.join(root, 'src', 'index.ts');

const files = (await fs.readdir(svgsDir)).filter(f => f.endsWith('.svg')).sort();
const entries = [];

for (const f of files) {
  const raw = await fs.readFile(path.join(svgsDir, f), 'utf8');
  const { data } = optimize(raw, {
    multipass: true,
    plugins: [
      'removeDimensions',
      { name: 'removeAttrs', params: { attrs: ['svg:width', 'svg:height'] } },
      { name: 'preset-default', params: { overrides: { removeViewBox: false } } }
    ]
  });
  const svg = data.replace('<svg ', '<svg aria-hidden="true" ').replace(/\n/g, '').replace(/>\s+</g, '><').trim();
  const name = f.replace(/\.svg$/i, '').replace(/[^a-z0-9_-]/gi, '');
  entries.push([name, svg]);
}

const typeUnion = entries.map(([n]) => JSON.stringify(n)).join(' | ') || 'never';
const map = entries.map(([n, s]) => `  ${n}: ${JSON.stringify(s)}`).join(',\n');

const out = `// AUTO-GENERATED by scripts/build-icons.mjs
export const icons = {
${map}
} as const;

export type IconName = ${typeUnion};
`;
await fs.writeFile(outFile, out, 'utf8');
console.log(`[icons] Wrote ${path.relative(root, outFile)} with ${entries.length} icons.`);
