name: Publish @josephaw1022/company-icons-icons
on:
  push:
    tags: ["icons-v*"]

jobs:
  publish-icons:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      # expose both; we'll pick NPM_TOKEN if set, else GITHUB_TOKEN
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: "@josephaw1022"

      - run: npm ci --workspaces
      - run: npm run build:icons

      # 🔐 npm login to GitHub Packages (non-interactive)
      - name: npm login (GitHub Packages)
        shell: bash
        run: |
          TOKEN="${NPM_TOKEN:-$GITHUB_TOKEN}"
          printf "%s\n%s\n%s\n" "$GITHUB_ACTOR" "$TOKEN" "actions@github.local" \
            | npm login \
                --registry=https://npm.pkg.github.com \
                --scope=@josephaw1022 \
                --auth-type=legacy \
                --always-auth

      - working-directory: packages/icons
        run: npm publish --access restricted --registry https://npm.pkg.github.com
