name: Publish @josephaw1022/company-icons-web
on:
  push:
    tags: ["icon-web-v*"]

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: "@josephaw1022"
          always-auth: true
      - run: npm ci --workspaces
      - run: npm run build:icons
      - run: npm run build:web
      - working-directory: packages/icon-web
        run: npm publish --access restricted --registry https://npm.pkg.github.com
